title: CV | Christos Tsiligiannis
description:  Christos Tsiligiannis CV
url: https://xristostsilis.github.io/jekyll-cv/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
